databaseChangeLog:
  - changeSet:
      id: 1.20.16
      author: GraviteeSource Team
      changes:
        - createTable:
            tableName: ${gravitee_prefix}commands
            columns:
              - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: from, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: to, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: content, type: nclob, constraints: { nullable: true } }
              - column: {name: expired_at, type: timestamp(6), constraints: { nullable: true } }
              - column: {name: created_at, type: timestamp(6), constraints: { nullable: true } }
              - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

        - addPrimaryKey:
            constraintName: pk_${gravitee_prefix}commands
            columnNames: id
            tableName: ${gravitee_prefix}commands

        - createTable:
            tableName: ${gravitee_prefix}command_acknowledgments
            columns:
              - column: {name: command_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: acknowledgment, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            constraintName: pk_${gravitee_prefix}command_acknowledgments
            columnNames: command_id, acknowledgment
            tableName: ${gravitee_prefix}command_acknowledgments

        - createTable:
            tableName: ${gravitee_prefix}command_tags
            columns:
              - column: {name: command_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: tag, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            constraintName: pk_${gravitee_prefix}command_tags
            columnNames: command_id, tag
            tableName: ${gravitee_prefix}command_tags