databaseChangeLog:
    - changeSet:
        id: 3.0.0
        author: GraviteeSource Team
        changes:
          - addColumn:
              tableName: plans
              columns:
                - column:
                    name: api
                    type: nvarchar(64)
                    constraints:
                      nullable: false;

          - sql:
              sql: update plans p set api = (select pa.api from plan_apis pa where pa.plan_id = p.id)

          - droptIndex:
              tableName: plan_apis
              indexName: idx_planapis_api

          - dropPrimaryKey:
              constraintName: pk_plan_apis
              tableName: plan_apis

          - dropTable:
              tableName: plan_apis

          - addColumn:
              tableName: pages
              columns:
                - column:
                    name: reference_id
                    type: nvarchar(64)
                    constraints:
                      nullable: false
                - column:
                    name: reference_type
                    type: nvarchar(32)
                    constraints:
                      nullable: false
          - sql:
              sql: update pages set reference_type='API', reference_id=api where api is not null
          - sql:
              sql: update pages set reference_type='ENVIRONMENT', reference_id='DEFAULT' where api is null
          - dropColumn:
              columnName: api
              tableName: pages

          - addColumn:
              tableName: ratings
              columns:
                - column:
                    name: reference_id
                    type: nvarchar(64)
                    constraints:
                      nullable: false
                - column:
                    name: reference_type
                    type: nvarchar(32)
                    constraints:
                      nullable: false
          - sql:
              sql: update ratings set reference_type='API', reference_id=api where api is not null
          - sql:
              sql: update ratings set reference_type='ENVIRONMENT', reference_id='DEFAULT' where api is null
          - dropColumn:
              columnName: api
              tableName: ratings

          - addColumn:
              tableName: identity_providers
              columns:
                - column:
                    name: reference_id
                    type: nvarchar(64)
                    constraints:
                      nullable: false
                - column:
                    name: reference_type
                    type: nvarchar(32)
                    constraints:
                      nullable: false
          - sql:
              sql: update identity_providers set reference_type='ENVIRONMENT', reference_id='DEFAULT'

          - addColumn:
              tableName: parameters
              columns:
                - column:
                    name: reference_id
                    type: nvarchar(64)
                    constraints:
                      nullable: false
                - column:
                    name: reference_type
                    type: nvarchar(32)
                    constraints:
                      nullable: false
          - sql:
              sql: update parameters set reference_type='ENVIRONMENT', reference_id='DEFAULT'

          - addColumn:
              tableName: roles
              columns:
                - column:
                    name: reference_id
                    type: nvarchar(64)
                    constraints:
                      nullable: false
                - column:
                    name: reference_type
                    type: nvarchar(32)
                    constraints:
                      nullable: false
          - sql:
              sql: update roles set reference_type='ORGANIZATION', reference_id='DEFAULT'
          - dropPrimaryKey:
              constraintName: pk_roles
              tableName: roles
          - addPrimaryKey:
              constraintName: pk_roles
              columnNames: scope, name, reference_id, reference_type
              tableName: roles

          - addColumn:
              tableName: role_permissions
              columns:
                - column:
                    name: reference_id
                    type: nvarchar(64)
                    constraints:
                      nullable: false
                - column:
                    name: reference_type
                    type: nvarchar(32)
                    constraints:
                      nullable: false
          - sql:
              sql: update role_permissions set reference_type='ORGANIZATION', reference_id='DEFAULT'
          - dropPrimaryKey:
              constraintName: pk_role_permissions
              tableName: role_permissions
          - addPrimaryKey:
              constraintName: pk_role_permissions
              columnNames: role_scope, role_name, reference_id, reference_type, permission
              tableName: role_permissions

          - addColumn:
              tableName: apis
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false
          - sql:
              sql: update apis set environment='DEFAULT'

          - addColumn:
              tableName: api_headers
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false
          - sql:
              sql: update api_headers set environment='DEFAULT'

          - addColumn:
              tableName: applications
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false
                - column:
                    name: picture
                    type: nclob
                    constraints:
                      nullable: true
          - sql:
              sql: update applications set environment='DEFAULT'

          - addColumn:
              tableName: commands
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false
          - sql:
              sql: update commands set environment='DEFAULT'

          - addColumn:
              tableName: dictionaries
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false
          - sql:
              sql: update dictionaries set environment='DEFAULT'

          - addColumn:
              tableName: entrypoints
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false
          - sql:
              sql: update entrypoints set environment='DEFAULT'

          - addColumn:
              tableName: events
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false
          - sql:
              sql: update events set environment='DEFAULT'

          - addColumn:
              tableName: groups
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false
          - sql:
              sql: update groups set environment='DEFAULT'

          - addColumn:
              tableName: users
              columns:
                - column:
                    name: reference_id
                    type: nvarchar(64)
                    constraints:
                      nullable: false
                - column:
                    name: reference_type
                    type: nvarchar(32)
                    constraints:
                      nullable: false
          - sql:
              sql: update users set reference_type='ENVIRONMENT', reference_id='DEFAULT'

          - addColumn:
              tableName: views
              columns:
                - column:
                    name: environment
                    type: nvarchar(64)
                    constraints:
                      nullable: false

          - sql:
              sql: update views set environment='DEFAULT'

          - createTable:
              tableName: environments
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: description, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: organization, type: nvarchar(64), constraints: { nullable: false } }
          - addPrimaryKey:
              constraintName: pk_environments
              columnNames: id
              tableName: environments
          - sql:
              sql: insert into environments (id, name, description, organization) values ('DEFAULT', 'Default environment', 'Default environment', 'DEFAULT')

          - createTable:
              tableName: environment_domain_restrictions
              columns:
                - column: {name: environment_id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: domain_restriction, type: nvarchar(64), constraints: { nullable: false } }

          - addPrimaryKey:
              constraintName: pk_environment_domain_restrictions
              columnNames: environment_id, domain_restriction
              tableName: environment_domain_restrictions

          - createTable:
              tableName: organizations
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: description, type: nvarchar(64), constraints: { nullable: true } }
          - addPrimaryKey:
              constraintName: pk_organizations
              columnNames: id
              tableName: organizations
          - sql:
              sql: insert into organizations (id, name, description) values ('DEFAULT', 'Default organization', 'Default organization')

          - createTable:
              tableName: organization_domain_restrictions
              columns:
                - column: {name: organization_id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: domain_restriction, type: nvarchar(64), constraints: { nullable: false } }

          - addPrimaryKey:
              constraintName: pk_organization_domain_restrictions
              columnNames: organization_id, domain_restriction
              tableName: organization_domain_restrictions

          - createTable:
              tableName: themes
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: reference_id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: reference_type, type: nvarchar(32), constraints: { nullable: false } }
                - column: {name: enabled, type: boolean, constraints: { nullable: false } }
                - column: {name: definition, type: nclob, constraints: { nullable: true } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }
                - column: {name: logo, type: nclob, constraints: { nullable: true } }
                - column: {name: optional_logo, type: nclob, constraints: { nullable: true } }
                - column: {name: background_image, type: nclob, constraints: { nullable: true } }
          - addPrimaryKey:
              constraintName: pk_themes
              columnNames: id
              tableName: themes
