databaseChangeLog:
    - changeSet:
        id: 1.19.0
        author: GraviteeSource Team
        changes:
        - createTable:
            tableName: dictionaries
            columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: description, type: nvarchar(4000), constraints: { nullable: true } }
                - column: {name: type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: state, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }
                - column: {name: deployed_at, type: timestamp(6), constraints: { nullable: true } }
                - column: {name: provider_type, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: provider_configuration, type: nvarchar(1000), constraints: { nullable: true } }
                - column: {name: trigger_rate, type: int, constraints: { nullable: true } }
                - column: {name: trigger_unit, type: nvarchar(64), constraints: { nullable: true } }

        - addPrimaryKey:
            constraintName: pk_dictionaries
            columnNames: id
            tableName: dictionaries

        - createTable:
            tableName: dictionary_property
            columns:
                - column: {name: dictionary_id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: k, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: v, type: nvarchar(1000), constraints: { nullable: false } }

        - addPrimaryKey:
            constraintName: pk_dictionary_property
            columnNames: dictionary_id, k, v
            tableName: dictionary_property