databaseChangeLog:
  - changeSet:
      id: 3.1.0
      author: GraviteeSource Team
      changes:
        - addColumn:
            tableName: apis
            columns:
              - column:
                  name: background
                  type: nclob
                  constraints:
                    nullable: true
        - addColumn:
            tableName: applications
            columns:
              - column:
                  name: background
                  type: nclob
                  constraints:
                    nullable: true
        - addColumn:
            tableName: categories
            columns:
              - column:
                  name: background
                  type: nclob
                  constraints:
                    nullable: true
