databaseChangeLog:
  - changeSet:
      id: 3.4.0
      author: GraviteeSource Team
      changes:
        - sql:
            - sql: update audits set reference_type = 'ORGANIZATION' where reference_type = 'PORTAL' and (event like 'IDENTITY_PROVIDER%' or event like 'ROLE%' or event like 'USER%' or (event like 'MEMBERSHIP%' and patch like '%organization%'));
        - sql:
            - sql: update audits set reference_type = 'ENVIRONMENT' where reference_type = 'PORTAL';

        - createTable:
            tableName: identity_provider_activations
            columns:
              - column: {name: identity_provider_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: reference_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: reference_type, type: nvarchar(32), constraints: { nullable: false } }
              - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
        - addPrimaryKey:
            constraintName: pk_identity_provider_activations
            columnNames: identity_provider_id, reference_id, reference_type
            tableName: identity_provider_activations
