databaseChangeLog:
  - changeSet:
      id: 3.4.0
      author: GraviteeSource Team
      changes:
        - sql:
            - sql: update audits set reference_type = 'ORGANIZATION' where reference_type = 'PORTAL' and (event like 'IDENTITY_PROVIDER%' or event like 'ROLE%' or event like 'USER%' or (event like 'MEMBERSHIP%' and patch like '%organization%'));
        - sql:
            - sql: update audits set reference_type = 'ENVIRONMENT' where reference_type = 'PORTAL';
