databaseChangeLog:
    - changeSet:
        id: 1.26.0
        author: GraviteeSource Team
        changes:
          - addColumn:
              tableName: client_registration_providers
              columns:
                - column:
                    name: initial_access_token
                    type: nvarchar(1000)
                - column:
                    name: initial_access_token_type
                    type: nvarchar(64)
          - dropNotNullConstraint:
              tableName: client_registration_providers
              columnName: client_id
              columnDataType: nvarchar(128)
          - dropNotNullConstraint:
              tableName: client_registration_providers
              columnName: client_secret
              columnDataType: nvarchar(128)
