databaseChangeLog:
  - changeSet:
      id: 3.8.0
      author: GraviteeSource Team
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}pages
            columns:
              - column:
                  name: visibility
                  type: nvarchar(64)
                  defaultValue: PUBLIC
                  constraints:
                    nullable: false