databaseChangeLog:
    - changeSet:
        id: 1.22.0
        author: GraviteeSource Team
        changes:

        - addColumn:
            tableName: keys
            columns:
                - column:
                    name: paused
                    type: boolean

        - addColumn:
            tableName: subscriptions
            columns:
                - column:
                    name: paused_at
                    type: timestamp(6)