databaseChangeLog:
    - changeSet:
        id: 1.30.0
        author: GraviteeSource Team
        changes:
          - createTable:
              tableName: ${gravitee_prefix}quality_rules
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: description, type: nvarchar(256), constraints: { nullable: false } }
                - column: {name: weight, type: int, constraints: { nullable: false } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

          - addPrimaryKey:
              constraintName: pk_${gravitee_prefix}quality_rules
              columnNames: id
              tableName: ${gravitee_prefix}quality_rules

          - createTable:
              tableName: ${gravitee_prefix}api_quality_rules
              columns:
                - column: {name: api, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: quality_rule, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: checked, type: boolean, constraints: { nullable: false } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

          - addPrimaryKey:
              constraintName: pk_${gravitee_prefix}api_quality_rules
              columnNames: api, quality_rule
              tableName: ${gravitee_prefix}api_quality_rules

          - createTable:
              tableName: ${gravitee_prefix}dashboards
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: reference_type, type: nvarchar(32), constraints: { nullable: false } }
                - column: {name: reference_id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: query_filter, type: nvarchar(128), constraints: { nullable: true } }
                - column: {name: order, type: int, constraints: { nullable: false } }
                - column: {name: enabled, type: boolean, constraints: { nullable: false } }
                - column: {name: definition, type: nclob, constraints: { nullable: true } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: true } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

          - addPrimaryKey:
              constraintName: pk_${gravitee_prefix}dashboards
              columnNames: id
              tableName: ${gravitee_prefix}dashboards

          - createIndex:
              indexName: idx_${gravitee_prefix}dashboards_reference_type
              columns:
                - column:
                    name: reference_type
                    type: nvarchar(32)
              tableName: ${gravitee_prefix}dashboards

          - addColumn:
              tableName: ${gravitee_prefix}client_registration_providers
              columns:
                - column:
                    name: software_id
                    type: nvarchar(256)

          - dropTable:
              cascadeConstraints: true
              tableName: ${gravitee_prefix}alerts

          - createTable:
              tableName: ${gravitee_prefix}alert_triggers
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: description, type: nvarchar(256), constraints: { nullable: true } }
                - column: {name: reference_type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: reference_id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: enabled, type: boolean, constraints: { nullable: false } }
                - column: {name: severity, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: definition, type: nclob, constraints: { nullable: false } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

          - addPrimaryKey:
              constraintName: pk_${gravitee_prefix}alert_triggers
              columnNames: id
              tableName: ${gravitee_prefix}alert_triggers
